import SwiftUI
import PDFKit

class PDFService {
    static let shared = PDFService()
    
    @MainActor
    func generateReadingSummary(user: AppUser, sessions: [ReadingSession]) -> URL? {
        let pdfMetaData = [
            kCGPDFContextCreator: "Library Companion",
            kCGPDFContextAuthor: user.name,
            kCGPDFContextTitle: "Reading Summary Report"
        ]
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]
        
        let pageWidth = 8.5 * 72.0
        let pageHeight = 11 * 72.0
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)
        
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("ReadingSummary_\(user.name).pdf")
        
        do {
            try renderer.writePDF(to: tempURL) { context in
                context.beginPage()
                
                var currentY: CGFloat = 40
                
                // 1. Header
                let titleFont = UIFont.systemFont(ofSize: 24, weight: .bold)
                let titleAttr = [NSAttributedString.Key.font: titleFont]
                "Reading Journey Summary".draw(at: CGPoint(x: 40, y: currentY), withAttributes: titleAttr)
                currentY += 40
                
                // 2. User Info
                let bodyFont = UIFont.systemFont(ofSize: 14, weight: .regular)
                let boldFont = UIFont.systemFont(ofSize: 14, weight: .bold)
                
                let userText = "Member: \(user.name)"
                userText.draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: boldFont])
                currentY += 20
                
                let dateText = "Generated on: \(Date().formatted(date: .long, time: .shortened))"
                dateText.draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: bodyFont])
                currentY += 40
                
                // 3. Stats
                let totalPoints = sessions.reduce(0) { $0 + ($1.minutes / 10) + $1.challengeBonus }
                let totalMins = sessions.reduce(0) { $0 + $1.minutes }
                
                let statsText = "Total Points: \(totalPoints)  |  Total Reading Time: \(totalMins) minutes"
                statsText.draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: boldFont])
                currentY += 40
                
                // 4. Table Header
                "Date".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: boldFont])
                "Book Title".draw(at: CGPoint(x: 140, y: currentY), withAttributes: [NSAttributedString.Key.font: boldFont])
                "Minutes".draw(at: CGPoint(x: 400, y: currentY), withAttributes: [NSAttributedString.Key.font: boldFont])
                "Points".draw(at: CGPoint(x: 500, y: currentY), withAttributes: [NSAttributedString.Key.font: boldFont])
                currentY += 25
                
                // Divider
                context.cgContext.setStrokeColor(UIColor.lightGray.cgColor)
                context.cgContext.setLineWidth(1)
                context.cgContext.move(to: CGPoint(x: 40, y: currentY))
                context.cgContext.addLine(to: CGPoint(x: 550, y: currentY))
                context.cgContext.strokePath()
                currentY += 15
                
                // 5. Session Rows
                for session in sessions.prefix(20) { // Limit to top 20 for one page sample
                    if currentY > pageHeight - 60 {
                        context.beginPage()
                        currentY = 40
                    }
                    
                    let dateStr = session.startedAt.formatted(date: .numeric, time: .omitted)
                    let bookTitle = session.book?.title ?? "Activity"
                    let mins = "\(session.minutes)"
                    let pts = "+\((session.minutes / 10) + session.challengeBonus)"
                    
                    dateStr.draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: bodyFont])
                    bookTitle.draw(in: CGRect(x: 140, y: currentY, width: 250, height: 20), withAttributes: [NSAttributedString.Key.font: bodyFont])
                    mins.draw(at: CGPoint(x: 400, y: currentY), withAttributes: [NSAttributedString.Key.font: bodyFont])
                    pts.draw(at: CGPoint(x: 500, y: currentY), withAttributes: [NSAttributedString.Key.font: bodyFont])
                    
                    currentY += 25
                }
                
                // Footer
                let footerText = "Generated by Library Companion App"
                footerText.draw(at: CGPoint(x: pageWidth/2 - 100, y: pageHeight - 40), withAttributes: [NSAttributedString.Key.font: bodyFont, NSAttributedString.Key.foregroundColor: UIColor.lightGray])
            }
            return tempURL
        } catch {
            print("Could not create PDF: \(error)")
            return nil
        }
    }

    @MainActor
    func generateCourierReceipt(user: AppUser, book: Book, points: Int) -> URL? {
        let pdfMetaData = [
            kCGPDFContextCreator: "Library Companion",
            kCGPDFContextAuthor: user.name,
            kCGPDFContextTitle: "Home Borrowing Pass"
        ]
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]
        
        let pageWidth = 6.0 * 72.0 // Receipt size
        let pageHeight = 8.0 * 72.0
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("CourierPass_\(book.title).pdf")
        
        do {
            try renderer.writePDF(to: tempURL) { context in
                context.beginPage()
                
                var currentY: CGFloat = 40
                
                // Header - Badge Style
                let badgeFont = UIFont.systemFont(ofSize: 28, weight: .black)
                let headerAttr = [NSAttributedString.Key.font: badgeFont, NSAttributedString.Key.foregroundColor: UIColor.systemIndigo]
                "OFFICIAL PASS".draw(at: CGPoint(x: 40, y: currentY), withAttributes: headerAttr)
                currentY += 40
                
                let subHeaderFont = UIFont.systemFont(ofSize: 18, weight: .bold)
                "Home Courier Challenge Won!".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: subHeaderFont])
                currentY += 50
                
                // Book Info
                let labelFont = UIFont.systemFont(ofSize: 12, weight: .bold)
                let valueFont = UIFont.systemFont(ofSize: 16, weight: .regular)
                
                "BOOK NAME:".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: labelFont, NSAttributedString.Key.foregroundColor: UIColor.gray])
                currentY += 15
                book.title.draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: valueFont])
                currentY += 40
                
                "HOME DELIVERY STATUS:".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: labelFont, NSAttributedString.Key.foregroundColor: UIColor.systemGreen])
                currentY += 15
                "Ready for Home Dispatch".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: valueFont, NSAttributedString.Key.foregroundColor: UIColor.systemGreen])
                currentY += 40
                
                "BORROW DATE:".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: labelFont, NSAttributedString.Key.foregroundColor: UIColor.gray])
                currentY += 15
                Date().formatted(date: .long, time: .omitted).draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: valueFont])
                currentY += 40
                
                let dueDate = Calendar.current.date(byAdding: .day, value: 14, to: Date())!
                "NEXT RETURN DATE:".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: labelFont, NSAttributedString.Key.foregroundColor: UIColor.red])
                currentY += 15
                dueDate.formatted(date: .long, time: .omitted).draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: valueFont, NSAttributedString.Key.foregroundColor: UIColor.red])
                currentY += 40
                
                "REWARDS WON:".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: labelFont, NSAttributedString.Key.foregroundColor: UIColor.gray])
                currentY += 15
                "+\(points) Points & Home Delivery".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: valueFont, NSAttributedString.Key.foregroundColor: UIColor.systemOrange])
                currentY += 50
                
                // Step-by-Step Section
                let stepFont = UIFont.systemFont(ofSize: 10, weight: .bold)
                let stepDetailFont = UIFont.systemFont(ofSize: 10, weight: .regular)
                
                "DISPATCH STEPS:".draw(at: CGPoint(x: 40, y: currentY), withAttributes: [NSAttributedString.Key.font: stepFont, NSAttributedString.Key.foregroundColor: UIColor.systemIndigo])
                currentY += 15
                
                let steps = [
                    "1. Verify Member ID at Exit",
                    "2. Confirm Book Eligibility (5-Min Challenge Passed)",
                    "3. Log Dispatch in Courier App",
                    "4. Deliver to Registered Member Address"
                ]
                
                for step in steps {
                    step.draw(at: CGPoint(x: 50, y: currentY), withAttributes: [NSAttributedString.Key.font: stepDetailFont])
                    currentY += 14
                }
                
                currentY += 20
                
                // QR Placeholder
                let footerFont = UIFont.systemFont(ofSize: 10, weight: .light)
                "Present this manifest for home delivery verification.".draw(at: CGPoint(x: 40, y: pageHeight - 60), withAttributes: [NSAttributedString.Key.font: footerFont])
                "ID: \(UUID().uuidString.prefix(8))".draw(at: CGPoint(x: 40, y: pageHeight - 45), withAttributes: [NSAttributedString.Key.font: footerFont])
            }
            return tempURL
        } catch {
            return nil
        }
    }

    @MainActor
    func generateBookingReceipt(user: AppUser, reservation: HallReservation) -> URL? {
        let pdfMetaData = [
            kCGPDFContextCreator: "Library Companion",
            kCGPDFContextAuthor: user.name,
            kCGPDFContextTitle: "Booking Confirmation"
        ]
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetaData as [String: Any]
        
        let pageWidth = 8.5 * 72.0
        let pageHeight = 11.0 * 72.0
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect, format: format)
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("Booking_\(reservation.id.uuidString.prefix(8)).pdf")
        
        do {
            try renderer.writePDF(to: tempURL) { context in
                context.beginPage()
                
                var currentY: CGFloat = 60
                
                // Header
                let titleFont = UIFont.systemFont(ofSize: 24, weight: .bold)
                let headerAttr = [NSAttributedString.Key.font: titleFont, NSAttributedString.Key.foregroundColor: UIColor.systemIndigo]
                "RESERVATION CONFIRMATION".draw(at: CGPoint(x: 60, y: currentY), withAttributes: headerAttr)
                currentY += 40
                
                // Member Info
                let labelFont = UIFont.systemFont(ofSize: 12, weight: .bold)
                let valueFont = UIFont.systemFont(ofSize: 14, weight: .regular)
                
                "MEMBER:".draw(at: CGPoint(x: 60, y: currentY), withAttributes: [NSAttributedString.Key.font: labelFont])
                user.name.draw(at: CGPoint(x: 150, y: currentY), withAttributes: [NSAttributedString.Key.font: valueFont])
                currentY += 25
                
                "DATE:".draw(at: CGPoint(x: 60, y: currentY), withAttributes: [NSAttributedString.Key.font: labelFont])
                reservation.bookingDate.formatted(date: .long, time: .shortened).draw(at: CGPoint(x: 150, y: currentY), withAttributes: [NSAttributedString.Key.font: valueFont])
                currentY += 40
                
                // Reservation Details Card
                let cardRect = CGRect(x: 60, y: currentY, width: pageWidth - 120, height: 180)
                let cardPath = UIBezierPath(roundedRect: cardRect, cornerRadius: 12)
                UIColor.systemGray6.setFill()
                cardPath.fill()
                
                var cardY = currentY + 20
                "HALL/LIBRARY:".draw(at: CGPoint(x: 80, y: cardY), withAttributes: [NSAttributedString.Key.font: labelFont])
                reservation.hallName.draw(at: CGPoint(x: 200, y: cardY), withAttributes: [NSAttributedString.Key.font: valueFont])
                cardY += 25
                
                "ADDRESS:".draw(at: CGPoint(x: 80, y: cardY), withAttributes: [NSAttributedString.Key.font: labelFont])
                reservation.hallAddress.draw(at: CGPoint(x: 200, y: cardY), withAttributes: [NSAttributedString.Key.font: valueFont])
                cardY += 25
                
                "TYPE:".draw(at: CGPoint(x: 80, y: cardY), withAttributes: [NSAttributedString.Key.font: labelFont])
                reservation.reservationType.rawValue.capitalized.draw(at: CGPoint(x: 200, y: cardY), withAttributes: [NSAttributedString.Key.font: valueFont])
                cardY += 25
                
                "DETAILS:".draw(at: CGPoint(x: 80, y: cardY), withAttributes: [NSAttributedString.Key.font: labelFont])
                reservation.reservationDetails.draw(at: CGPoint(x: 200, y: cardY), withAttributes: [NSAttributedString.Key.font: valueFont])
                cardY += 25
                
                "ATTENDEES:".draw(at: CGPoint(x: 80, y: cardY), withAttributes: [NSAttributedString.Key.font: labelFont])
                "\(reservation.attendeeCount)".draw(at: CGPoint(x: 200, y: cardY), withAttributes: [NSAttributedString.Key.font: valueFont])
                
                currentY += 220
                
                // QR Code Note
                "SECURITY VERIFICATION".draw(at: CGPoint(x: 60, y: currentY), withAttributes: [NSAttributedString.Key.font: labelFont, NSAttributedString.Key.foregroundColor: UIColor.systemIndigo])
                currentY += 20
                "Please present the QR code displayed in the app for access. This document serves as a receipt and proof of booking.".draw(in: CGRect(x: 60, y: currentY, width: pageWidth - 120, height: 40), withAttributes: [NSAttributedString.Key.font: valueFont])
                
                // Footer
                let footerFont = UIFont.systemFont(ofSize: 10, weight: .light)
                "Booking ID: \(reservation.id.uuidString)".draw(at: CGPoint(x: 60, y: pageHeight - 80), withAttributes: [NSAttributedString.Key.font: footerFont])
            }
            return tempURL
        } catch {
            return nil
        }
    }
}
